version: '3.8'

services:
  ffc-grants-eoi:
    build:
      context: .
      target: production
    image: ffc-grants-eoi
    environment:
      NODE_ENV: production
      EOI_QUEUE_ADDRESS: ffc-grants-eoi-${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
